languagename = "English"
title = "Leo Carvalho"

[params]
info = "Full Stack DevOps and Magician"
description = "John Doe's personal website"
keywords = "blog,developer,personal"

[menu]

[[menu.main]]
  name = "About"
  weight = 1.0
  url = "/about/"

[[menu.main]]
  name = "Blog"
  weight = 2.0
  url = "/posts/"