languagename = "🌐 \u00a0\u00a0 🇺🇸/🇬🇧"
title = "Leo Carvalho"

[params]
info = "Back-end developer, development teacher, and Ph.D. in bad jokes"
description = "Leo Carvalho is a back-end developer (Node.js, PHP and C#) and development teacher. Christian, 25y, graduated in Systems' Analysis and Development on Estácio and single until now."
keywords = "leo carvalho, c# developer, node developer, node.js developer, php developer, .net, c#, node, node.js, javascript, back-end developer, expressjs, git, github, technical blog, tech blog, tutorial, blog"

[menu]

[[menu.main]]
  name = "About me"
  weight = 1.0
  url = "/about/"

[[menu.main]]
    name = "Legal"
    weight = 1.5
    url = "/terms/"